[package]
name = "snpick"
version = "0.1.0"
edition = "2021"

[dependencies]
bio = "2.0.3"
rayon = "1.7.0"
clap = { version = "4.1.8", features = ["derive"] }
indicatif = "0.17.3"
chrono = "0.4"
sysinfo = "0.29.11"
